### ISSUE TITLE
asking for help

### ISSUE THREAD

**Issue by anisbouzahar** [WilixLead/iWownController#12]
hello, am trying to build an app some how similar to yours, could you share the GATT SERVICES,and characteristics  technical documents? or just point me to where i can find them, appreciated.

**Comment by felixcastrofuentes** [comment]
@anisbouzahar can you find the documents? I need them too!

**Comment by anisbouzahar** [comment]
@felixcastrofuentes  I could not put my hands on the specs,but i came across something on an other issue of this repository, @WilixLead  says in a comment , he is reverse engineering the Zeroner app  [#issue]( https://github.com/WilixLead/iWownController/issues/3/#issuecomment-178586918, ),I suspect there is no actual source for  the specs document. if something comes up,ill be more than happy to share.

**Comment by felixcastrofuentes** [comment]
@anisbouzahar I found the documentation and sdk: http://wechat.iwown.com/devcenter/home.html#
:) Good look!

**Comment by anisbouzahar** [comment]
I actually spent a while looking for that,  thank you @felixcastrofuentes, do you know if the sdk gets updated quiet often?
